#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
# rustup completion
# https://github.com/rust-lang-nursery/rustup.rs#enable-tab-completion-for-bash-fish-or-zsh
fpath+=~/.zfunc

alias ta='tmux attach'

# Golang settings
export GOPATH=~/go
export PATH=$PATH:~/go/bin

# pip installed executables
export PATH=$PATH:~/.local/bin
# aws-cli command completion
source ~/.local/bin/aws_zsh_completer.sh

# Rust
export PATH="$HOME/.cargo/bin:$PATH"
# Rust source path
export RUST_SRC_PATH=$(rustc --print sysroot)/lib/rustlib/src/rust/src
